[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86-64-crab_os.json"

[target.'cfg(target_os= "none")']
runner = "bootimage runner"